name: CI
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.version }}

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Run core tests
      run: yarn test
      working-directory: core

  Documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Install documentation dependencies
      run: yarn
      working-directory: tsdoc

    - name: Build documentation
      run: yarn build
      working-directory: tsdoc

    - name: Run documentation tests
      run: yarn test
      working-directory: tsdoc

  Compiler-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14, 16, 18]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.version }}

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Install compiler test dependencies
      run: yarn
      working-directory: compiler-tests

    - name: Run typescript tests
      run: yarn typescript
      working-directory: compiler-tests

    - name: Run parcel tests
      run: yarn parcel
      working-directory: compiler-tests

    - name: Run rollup tests
      run: yarn rollup
      working-directory: compiler-tests

    - name: Run vite tests
      run: yarn vite
      working-directory: compiler-tests