name: CI
on: push

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    
    - name: Install dependencies
      run: yarn
      
    - name: Build
      run: yarn build
    
    - name: Run tests
      run: yarn test

    - name: Install compiler test dependencies
      run: yarn
      working-directory: compiler-tests

    - name: Run typescript tests
      run: yarn typescript
      working-directory: compiler-tests

    - name: Run parcel tests
      run: yarn parcel
      working-directory: compiler-tests

    - name: Run rollup tests
      run: yarn rollup
      working-directory: compiler-tests

    - name: Run vite tests
      run: yarn vite
      working-directory: compiler-tests