name: CI
on: [ push, pull_request ]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Run core tests
      run: yarn test
      working-directory: core

  Documentation:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Install documentation dependencies
      run: yarn
      working-directory: tsdoc

    - name: Build documentation
      run: yarn build
      working-directory: tsdoc

    - name: Run documentation tests
      run: yarn test
      working-directory: tsdoc

  Compiler-Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.version }}

    - name: Install core dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Install compiler test dependencies
      run: yarn
      working-directory: compiler-tests

    - name: Run compiler tests
      run: yarn all
      working-directory: compiler-tests