name: npm
on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.ref}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn
        working-directory: core

      - name: Build
        run: yarn build
        working-directory: core

      - name: Test
        run: yarn test
        working-directory: core

      - name: Copy Readme
        run: cp README.md core

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: core/package.json
          token: ${{ secrets.NPM_TOKEN }}
          check-version: false
