name: Sonar
on: push

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install c8
      run: yarn global add c8

    - name: Install dependencies
      run: yarn
      working-directory: core

    - name: Build core
      run: yarn build
      working-directory: core

    - name: Get core code coverage
      run: c8 -r lcov yarn test -s
      working-directory: core

    - name: Install documentation dependencies
      run: yarn
      working-directory: tsdoc

    - name: Build documentation
      run: yarn build
      working-directory: tsdoc

    - name: Get documentation code coverage
      run: c8 -r lcov yarn test -s
      working-directory: tsdoc

    - name: SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}