name: Sonar
on: push

jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Install c8
      run: yarn global add c8
    
    - name: Install dependencies
      run: yarn
    
    - name: Build
      run: yarn build

    - name: Get code coverage
      run: c8 -r lcov yarn test -s
      
    - name: SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}